### ISSUE TITLE
Trūksta aprašymo vartototjui

### ISSUE THREAD

**Issue by DenisTimofijuk** [recallfx/elektros-kainu-skaiciuokle#1]
Puikus projektukas, tik trūksta daugiau teksto vartototjui atsidarius produktą per **github pages**. Nėra aišku, kokius tiksliai duomenis reikia suvesti, ar vartojimą per mėnesį, ar per metus. Lengvas tekstas index puslapyje vartotojui toks kaip "kas tai" ir "kaip naudotis", būtų labai paranku.

**Comment by recallfx** [comment]
Pridėta čia: https://github.com/recallfx/elektros-kainu-skaiciuokle/pull/3/commits/e940a056ce05ebbf2164b4a4666acbee384eba53
